### ISSUE TITLE
Property Export: Distribution axis and overall layout.

### ISSUE THREAD

**Issue by alab0329** [scanberg/viamd#26]
The axis for data exported example rdf is off. 
![Rdf](https://user-images.githubusercontent.com/3403913/226847001-a7dedde1-1db9-4d33-8a21-c193c6896f65.png)

**Comment by scanberg** [comment]
There are more things out of order with the radial distribution function in the current state.
You have probably noticed that the distribution is off because it incorrectly adds a large portion of the distribution around zero, which is a bug stemming from the spatial hash that internally uses cell-quantized coordinates and therefore the distance between the atoms may not be zero when they in fact are. This incorrectly populates the zero bin which should not be the case.

As for the x coordinate label, I'll look into it :)

**Comment by scanberg** [comment]
The distribution is fixed, there was some inherent bug in the spatial acceleration structure... 
I'm hijacking this issue (again) and converting it back to an issue just regarding property export.

**Comment by alab0329** [comment]
![rdf3_zoom](https://user-images.githubusercontent.com/3403913/228531037-f608f777-d82e-4d90-be91-27d7976cfe0d.png)
![rdf3](https://user-images.githubusercontent.com/3403913/228531040-b8ed7f6c-b76b-4b0b-afea-241b18ad9130.png)
I would double check the normalization something still seems off. But again this can to some extent be due to these results are from the membrane dataset. As a side note a y axis for rdf in viamd would have been nice.

**Comment by scanberg** [comment]
This has now been resolved, and the x-axis should be formatted appropriately.
