### ISSUE TITLE
Support for AMBER and small issues

### ISSUE THREAD

**Issue by SSchott** [scanberg/viamd#37]
Hi. Thanks for the nice viewer :+1:  Any chance to get support for AMBER files, particularly parm7 and netCDF formats? Right now one can do transformations with parmed, but that is not ideal. 

I also had two issues until now while running the program (as compiled from a cloned repo yesterday, 29.11.2023):
1) Got a core dumped while passing the mouse over a script with selections:
```
Assertion "get_identifier(ir, name) == NULL" failed at line 1059 in /viamd/ext/mdlib/src/md_script.c:create_identifier 
Illegal instruction (core dumped)
```
2) I defined a distance measurement, and ran the evaluation, but no plot was generated. The plot area had inf,inf as the min.max boundaries, but no data was displayed even when modifying the plot region. Exporting the data shows the expected values though.

**Comment by mathieulinares** [comment]
Thanks for you interest. We do not support AMBER files for the moment, we are planning to do so in the future but we are a small team and cannot promise any deadline for the moment. We will communicate about it in the future.

Regarding your first point, could you tell me your os and hardware? We are going to have a look at it.

Regarding your second point: After a property is eveluated (Evaluate buttton or SHIFT + ENTER) it is NOT automatically displayed in the timeline or in the distribution. We do not allow that because if many properties are defined your timeline and distribution will become extremely cluttered. For that reason you need to click on Properties (in the timeline and distribution) and drag and drop the properties you are interested in. You can adjust the number of subplots.

Let us know if something is not clear.

**Comment by scanberg** [comment]
Hi @SSchott,
Thanks for the report, there are a lot of hard assertions in the script. But they should never be present to the end user (ideally!) I cannot say what went wrong on this occasion without examining the full script. But I have softened this assertion into a check with a logged error just in case.

Also, as Mathieu pointed out, all scripts and properties require evaluation before they can be visualized.
To visualize a property: drag and drop any property listed within the menu 'Properties' in a visualization window to create a representation for it.

![properties](https://github.com/scanberg/viamd/assets/706523/29f8d5d8-4ec6-4506-8bb8-f687e3b65bd5)

**Comment by scanberg** [comment]
Well, that should certainly not occur. I will try to replicate the issue on my machine, thanks for the info.

**Comment by SSchott** [comment]
> You need to drag and drop the property to the timeline (distribution). Just not click it.

Aha, missed that! Thanks, works.

I am adding a third one.

3) By loading a huge gro file, I got the following:
```
[13:28:50][error]: One or more arguments are missing [md_gl_molecule_set_atom_flags]
Assertion "ci < cell_count" failed at line 737 in /viamd/ext/mdlib/src/core/md_spatial_hash.c:md_spatial_hash_create_soa
Illegal instruction (core dumped)
```

**Comment by SSchott** [comment]
>  In any case, such big system will definitely push the limit of VIAMD.

That was the idea :slightly_smiling_face: If looking for a potential VMD upgrade, I have to put it to the limit :sweat_smile: 

Tried with smaller systems with a freshly compiled and `git pull`ed version, and crashes as well if I have lipids with the same message:

```
[15:13:51][error]: One or more arguments are missing [md_gl_molecule_set_atom_flags]
Assertion "ci < cell_count" failed at line 737 in /viamd/ext/mdlib/src/core/md_spatial_hash.c:md_spatial_hash_create_soa
Illegal instruction (core dumped)
```

so I guess the lipid definitions within AMBER systems is unhappy in VIAMD. PDB files fail as well.

Thanks for looking into these issues. I will check the project again in some time :+1:

**Comment by SSchott** [comment]
Seems the issue relates to whenever there are more than 99,999 atoms in the gro file. netCDF and parm7 doesn't have this issues :wink: 

Attached you find some files to play with. Be aware that internally top is parm7, crd is a netCDF file.
[send.tar.gz](https://github.com/scanberg/viamd/files/13515692/send.tar.gz)

**Comment by mathieulinares** [comment]
![Screenshot from 2023-11-30 18-17-27](https://github.com/scanberg/viamd/assets/38646069/92503c80-97f9-43ba-b0d1-c23637ef8ea6)
I do not have any issue to look at your gro and xtc. Neither with the pdb. I have regularly playing with gro file larger then 99,999 atoms without any issue. 
I don't understand what the issue is but we will investigate. Stay tuned. Cheers.
