### ISSUE TITLE
importing .csv files

### ISSUE THREAD

**Issue by FlorianWieser1** [scanberg/viamd#46]
Dear authors,
 
First of all thank you for this project, this was really missing!
However, I'm not sure how to import external data. Specifically I ran a simulation with AMBER, converted the trajectory to .pdb and read out the total energy and saved it as .csv. The trajectory itself can be loaded, everything works fine. Now I want to have the corresponding energies beeing displayed in the timelines window. 
I added the following to script editor "energy = import("/home/weasel/tolocal/energy.csv");" The path is found but I always get the error "number of columns in row 2 does not match the first row [parse]". This is how my .csv looks like:
time,energy
0.000,-181969.0759
0.100,-148270.2830
0.200,-140970.5800
0.300,-135127.0550
0.400,-130371.7956
0.500,-126459.5568
0.600,-123288.7108
0.700,-120653.1827
0.800,-118417.1584
0.900,-116522.2044
1.000,-115009.6799
1.100,-113757.2837
1.200,-112564.0433
...

Adding/removing the header or columns did not help. What am I missing?

Thank you in advance and best regards!

**Comment by mathieulinares** [comment]
Thanks @FlorianWieser1, would you mind sharing your data with us (pdb+csv)? It would make it easier for us to make sure of what is going on. We are in any cases investigating the issue.
Best

**Comment by FlorianWieser1** [comment]
Thank you @mathieulinares for your quick reply. I'm happy to share the files with you. Can you provide me an email?

**Comment by mathieulinares** [comment]
I just dropped you an email.

**Comment by scanberg** [comment]
If there are time stamps available in the energies and the trajectory, then we match on timestamps.
If we cannot use the timestamps, then we do a simple match on the number of frames.
This means in your case, if you are limited to PDBs (since we do not support AMBER yet) you have to provide tables that match in length with number of frames.

What we could potentially do in the latter case is to check if the table length is an even multiple of the number of frames, then we could also just extract every N'th frame in that case.

Best,
Robin
