### ISSUE TITLE
<< Loading PDB error >>

### ISSUE THREAD

**Issue by icamps** [scanberg/viamd#50]
Hi.

I tried to load a PDB with multiple modes of a boron-nitride nanotube surrounded by water molecules and got the following error:

```
Assertion "cell_data[ci] < LENGTH_CAP && "Too many entities per cell"" failed at line 740 in /home/icamps/Downloads/viamd/ext/mdlib/src/core/md_spatial_hash.c:md_spatial_hash_create_soa
Illegal instruction (core dumped)
```

Any ideas about this?

Thanks in advance.

**Comment by scanberg** [comment]
Hi @icamps,
Thanks for reaching out.
That's an internal error in the spatial hash function. It probably means that it could not resolve the dimensions of the box correctly, and if it's periodic, too many particles end up in the same cell. (This should be softened into an error that we can recover from rather than being a hard assertion).
Would you be willing to share the PDB file so I can take a look?

Best regards,
Robin

**Comment by scanberg** [comment]
I see,
Would you be willing to share a snipped of the PDB or the file in some way or form?
It would help alot in order to replicate the issue on my machine to debug it.

Thanks,
Robin

**Comment by scanberg** [comment]
I've seen this issue on some other rare occasion where the coordinates were not supplied in Ångströms. This could potentially be something to check for until there is some fix from my end.

Best,
Robin

**Comment by mathieulinares** [comment]
@icamps, did you manage to solve the issue? Can we help?

**Comment by mathieulinares** [comment]
Alright @icamps 
Since we don't have any answer for you, we are going to close this issue. 
Feel free to come back to us.
Mathieu
