### ISSUE TITLE
`*` operator does not work as expected together with `/` operator in the script language

### ISSUE THREAD

**Issue by DavidCdeB** [scanberg/viamd#70]
Hi, thanks again for this program. 

It looks like the `*` operator does not work as expected together with  `/` operator in the script language:

MWE:

```
a = distance(20, 789);
b = 0.2 * (a + 2);
c = 1/5 * (a + 2);
```

`b` and `c` should give the same result. However, `c` looks like it's zero as one can check in the Timeline:

![fractions_and_mult](https://github.com/scanberg/viamd/assets/18029016/d2d8a48c-6bef-4848-8ffb-cdd4269d7411)

Embedding 1/5 in parenthesis, i.e. `c = (1/5) * (a + 2)` shows no  `c` in the Timeline:
![fractions_2](https://github.com/scanberg/viamd/assets/18029016/dcf4f432-02b2-47ec-be55-04a09d7f8de3)

This potential bug can potentially prevent from writing more complex formulas in the script editor.

**Comment by scanberg** [comment]
@DavidCdeB 
Thanks for the report!
This is due to the fact that the / operator is applied to two integers which defaults to integer divide :/.
So if you do 1.0/5 or 1/5.0 it should result to the correct value of 0.2.

We may want to change the default behavior in this case to default to floating point operations for division and introduce something makes the integer operation more explicit.

Best,
Robin
